kind: project
metadata:
  name: testing-workdir-shapira
  created: '2023-03-26T07:22:52.792000'
spec:
  functions:
  - name: add-1
    kind: job
    image: mlrun/mlrun
    handler: add_1.add_1
  - name: add-2
    kind: job
    image: mlrun/mlrun
    handler: add_2.add_2
  workflows:
  - path: ./project/workflow.py
    name: main
  artifacts: []
  conda: ''
  source: git://github.com/GiladShapira94/test-working-dir.git#master
  subpath: ./project
  load_source_on_run: false
  desired_state: online
  owner: shapira
status:
  state: online
